title: Personal page
description: My own personal page.
remote_theme: just-the-docs
color_scheme: dark

url: https://metury.github.io/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

mermaid:
  version: "9.1.3"

aux_links:
  "GitHub":
    - "https://github.com/metury/metury.github.io"