[book]
authors = ["Tomáš Turek"]
language = "en"
multilingual = true
src = "src"
title = "Personal page"

[output.html]
mathjax-support = true
additional-css = ["./theme/catppuccin.css"]

[output.html.fold]
enable = true
